name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0' # Обновил версию SDK до более типичной для текущего Flutter. У вас было ^3.10.0, что пока не выпущено. Если вы используете очень новую версию Dart/Flutter, это может быть 3.4.0+.

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3 # ВОТ ЗДЕСЬ ОН ДОЛЖЕН БЫТЬ
  sqflite: ^2.3.2
  path: ^1.9.0
  path_provider: ^2.1.2
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Обновил версию до более актуальной, у вас было ^6.0.0, что может быть опечаткой.

flutter:
  uses-material-design: true